apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: identity-service
  name: identity-service
  namespace: default
spec:
  replicas: 1 #CHANGE
  minReadySeconds: 45
  selector:
    matchLabels:
      app: identity-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - image: vebstechbee03/tech-bee:identity-service-latest
        imagePullPolicy: Always
        name: identity-service
        ports:
        - containerPort: 8085
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: uat