apiVersion: v1
kind: Service
metadata:
  name: identity-service-nodeport
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 8085
      nodePort: 30002
  selector:
    app: identity-service